api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    swarmMode: true
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: test@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web